In [1]:
# value_counts()

import pandas as pd

data = {
    "status": ["Up", "Down", "Up", "Down", "Up"]
}

df = pd.DataFrame(data)

In [2]:
df["status"].value_counts()

status
Up      3
Down    2
Name: count, dtype: int64

In [4]:
# Check for Missing Data

import pandas as pd

data = {
    "server": ["WEB01", "WEB02", "WEB03"],
    "cpu": [35, None, 45]
}

df = pd.DataFrame(data)

In [5]:
# Find Missing Values

df.isnull()

   server    cpu
0   False  False
1   False   True
2   False  False

In [6]:
# Count Missing Values

df.isnull().sum()

server    0
cpu       1
dtype: int64

In [7]:
# Removing Missing Values

df.dropna()

  server   cpu
0  WEB01  35.0
2  WEB03  45.0

In [9]:
# Filling Missing Values
#Instead of deleting

df["cpu"] = df["cpu"].fillna(0)

In [10]:
df.isnull()

   server    cpu
0   False  False
1   False  False
2   False  False

In [11]:
# Removing Duplicate Records

data = {
    "server": ["WEB01", "WEB02", "WEB02", "WEB03"]
}

df = pd.DataFrame(data)

In [12]:
df.drop_duplicates()

  server
0  WEB01
1  WEB02
3  WEB03

In [13]:
df["server"].value_counts()

server
WEB02    2
WEB01    1
WEB03    1
Name: count, dtype: int64

In [16]:
import pandas as pd

data = {
    "server": ["WEB01", "WEB02", "WEB02", "WEB03", "WEB04"],
    "status": ["Up", "Down", "Down", "Up", "Down"]
}

df = pd.DataFrame(data)

In [17]:
df["status"].value_counts()

status
Down    3
Up      2
Name: count, dtype: int64

In [18]:
df.drop_duplicates()

  server status
0  WEB01     Up
1  WEB02   Down
3  WEB03     Up
4  WEB04   Down